<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://music_and_movie_prj" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://music_and_movie_prj" xmlns:intf="http://music_and_movie_prj" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://music_and_movie_prj" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="search_movie">
    <complexType>
     <sequence>
      <element name="name" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="search_movieResponse">
    <complexType/>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="search_movieRequest">

      <wsdl:part element="impl:search_movie" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="search_movieResponse">

      <wsdl:part element="impl:search_movieResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="searching">

      <wsdl:operation name="search_movie">

         <wsdl:input message="impl:search_movieRequest" name="search_movieRequest">

       </wsdl:input>

         <wsdl:output message="impl:search_movieResponse" name="search_movieResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="searchingSoapBinding" type="impl:searching">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="search_movie">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="search_movieRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="search_movieResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="searchingService">

      <wsdl:port binding="impl:searchingSoapBinding" name="searching">

         <wsdlsoap:address location="http://localhost:8080/music_and_movie_prj/services/searching"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
