<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://music_and_movie_prj" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://music_and_movie_prj" xmlns:intf="http://music_and_movie_prj" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://music_and_movie_prj" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="getFeedback">
    <complexType>
     <sequence>
      <element name="Email" type="xsd:string"/>
      <element name="category" type="xsd:string"/>
      <element name="comment" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
   <element name="getFeedbackResponse">
    <complexType/>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="getFeedbackResponse">

      <wsdl:part element="impl:getFeedbackResponse" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="getFeedbackRequest">

      <wsdl:part element="impl:getFeedback" name="parameters">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="Feedback">

      <wsdl:operation name="getFeedback">

         <wsdl:input message="impl:getFeedbackRequest" name="getFeedbackRequest">

       </wsdl:input>

         <wsdl:output message="impl:getFeedbackResponse" name="getFeedbackResponse">

       </wsdl:output>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="FeedbackSoapBinding" type="impl:Feedback">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getFeedback">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getFeedbackRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getFeedbackResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="FeedbackService">

      <wsdl:port binding="impl:FeedbackSoapBinding" name="Feedback">

         <wsdlsoap:address location="http://localhost:8080/music_and_movie_prj/services/Feedback"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
